## A simple entity blocker that prevents certain entities from spawning.

# The list of entities to block, e.g. ``["minecraft:villager"]``.
blockedEntities = [
    "minecraft:cow",
    "minecraft:sheep",
    "minecraft:chicken",
    "minecraft:bat",
    "minecraft:squid",
    "minecraft:glow_squid",
    "minecraft:cod",
    "minecraft:dolphin",
    "minecraft:salmon",
    "minecraft:goat",
    "minecraft:pufferfish",
    "minecraft:panda",
    "minecraft:polar_bear",
    "minecraft:iron_golem",
    "minecraft:rabbit",
    "minecraft:llama",
    "minecraft:turtle",
    "minecraft:wolf",
    "minecraft:pig",
    "minecraft:fox",
    "minecraft:frog",
    "minecraft:strider",
    "minecraft:piglin",
    "minecraft:piglin_brute",
    "minecraft:zombified_piglin",
    "minecraft:bee",
]
