version: 2

build:
    os: ubuntu-24.04
    tools: {python: "3.12"}
    jobs:
        post_install:
            - "pip install --upgrade pdm"
            - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH pdm install

sphinx:
  configuration: docs/source/conf.py
