
#.
#Common config
[common]
	#.
	#stress * rpm = total stress
	#(Can be overridden by custom generator types)
	#Range: > 0
	generatorStress = 8
	#.
	#(Can be overridden by custom generator types)
	#Range: > 1
	maxGeneratorStorage = 256
	#.
	#(Can be overridden by custom generator types)
	#Range: 0.0 ~ 3.4028234663852886E38
	outputPerSecondPerRpm = 2.5
	#.
	#Log information that may be usefull for reporting a problem and debugging it.
	#THIS WILL SPAM YOUR LOGS
	enableDebugLogging = false

	#.
	#Cobblestone generator types
	[common.generatorsEnabled]
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		cobblestoneGeneratorEnabled = true
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		basaltGeneratorEnabled = false
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		stoneGeneratorEnabled = false
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		limestoneGeneratorEnabled = false
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		scoriaGeneratorEnabled = false
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		#(Also requires deepslate generators datapack, https://modrinth.com/datapack/create-cobblestone-deepslate-generators)
		deepslateGeneratorEnabled = false
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		#(Also requires deepslate generators datapack, https://modrinth.com/datapack/create-cobblestone-deepslate-generators)
		cobbledDeepslateGeneratorEnabled = false

