
#.
#Common config
[common]
	#.
	#Default generator stress
	#stress * rpm = total stress
	#(Can be overridden by custom generator types)
	#Range: > 0
	generatorStress = 8
	#.
	#Default generator ratio
	#Cobblestone/tick = rpm/ratio
	#(Can be overridden by custom generator types)
	#Range: 0.009999999776482582 ~ 3.4028234663852886E38
	generatorRatio = 8.0
	#.
	#Default maximum storage of the generators in items
	#(Can be overridden by custom generator types)
	#Range: > 1
	maxGeneratorStorage = 256

	#.
	#Cobblestone generator types
	[common.generatorsEnabled]
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		cobblestoneGeneratorEnabled = true
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		basaltGeneratorEnabled = false
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		stoneGeneratorEnabled = false
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		limestoneGeneratorEnabled = false
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		scoriaGeneratorEnabled = false
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		#(Also requires deepslate generators datapack, https://modrinth.com/datapack/create-cobblestone-deepslate-generators)
		deepslateGeneratorEnabled = false
		#.
		#Enables the generator. When disabled, the generator is replaced with unset generators. Make a backup before doing this.
		#(Also requires deepslate generators datapack, https://modrinth.com/datapack/create-cobblestone-deepslate-generators)
		cobbledDeepslateGeneratorEnabled = false

