
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				horse = true
				minecart = true
				item = true
				donkey = true
				furnace_minecart = true
				chest_minecart = true
				experience_orb = true
				player = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				super_glue = true

			[light_sources.settings.entities.littlelogistics]
				seater_car = true
				steam_locomotive = true
				fluid_car = true

