
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				item = true
				bee = true
				donkey = true
				wither_skeleton = true
				furnace_minecart = true
				chest_minecart = true
				strider = true
				item_frame = true
				horse = true
				skeleton = true
				minecart = true
				zombified_piglin = true
				piglin = true
				hoglin = true
				camel = true
				cat = true
				witch = true
				drowned = true
				parrot = true
				experience_orb = true
				lightning_bolt = true
				player = true

			[light_sources.settings.entities.surface]
				grizzly_bear = true

			[light_sources.settings.entities.gtceu]
				dynamite = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				stationary_contraption = true
				gantry_contraption = true
				super_glue = true

			[light_sources.settings.entities.littlelogistics]
				tug = true
				seater_car = true
				steam_locomotive = true
				fluid_car = true
				seater_barge = true

