
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				item = true
				minecart = true
				bee = true
				furnace_minecart = true
				experience_orb = true
				chest_minecart = true
				player = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				super_glue = true

