# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				donkey = true
				chest_minecart = true
				fox = true
				pig = true
				allay = true
				mule = true
				piglin = true
				hoglin = true
				blaze = true
				camel = true
				rabbit = true
				cat = true
				drowned = true
				ghast = true
				sheep = true
				experience_orb = true
				player = true
				item = true
				wolf = true
				elder_guardian = true
				furnace_minecart = true
				horse = true
				minecart = true
				mooshroom = true
				glow_item_frame = false
				parrot = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				super_glue = true

			[light_sources.settings.entities.bigglobe]
				rock = true

