name: Automatic Build

# no pull request building, don't need it quite frankly
on:
    push:
        branches: [mizuki, ena]

jobs:
    build-mrpack:
        name: "Build .mrpack file"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v4"
              with:
                fetch-depth: 0

            - name: "Install Python"
              uses: actions/setup-python@v5
              with:
                # required for Kamuidrome
                python-version: "3.12" 

            - name: Install PNPM
              uses: pnpm/action-setup@v4

            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: "22.4.1"
                cache: "pnpm"

            - name: Install PNPM packages
              run: pnpm install
            
            - name: Install PDM and virtualenv
              run: pip install -U pdm && pdm install

            - name: Build KubeJS scripts
              run: pnpm run build-dev  # meh, who cares about minaturising.
            
            - name: Build Quests
              run: ./build_quests.sh
            
            # TODO: add CI mode to Kamuidrome
            - name: Export client-side modpack
              run: mkdir -p ./output && pdm run kamuidrome export "output/Bigger Industrialisation (Client)"

            - name: Export server-side modpack
              run: pdm run kamuidrome export "output/Bigger Industrialisation (Server-Only)"
    
            - name: Upload combined zip
              uses: "actions/upload-artifact@v4"
              with:
                name: "BI-${{ github.head_ref || github.ref_name }}-${{ github.sha }}.mrpack"
                path: "output"
                compression-level: 0
