name: Automatic Build

# no pull request building, don't need it quite frankly
on:
    push:
        branches: [mizuki, ena]

jobs:
    build-mrpack-client:
        name: "Build .mrpack file"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v4"
              with:
                fetch-depth: 0

            - name: "Install Python"
              uses: actions/setup-python@v5
              with:
                # required for Kamuidrome
                python-version: "3.12" 

            - name: Install PNPM
              uses: pnpm/action-setup@v4

            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: "latest"
                cache: "pnpm"
            
            - name: Install Kamuidrome
              run: pip install -U git+https://github.com/Fuyukai/Kamuidrome.git
            
            - name: Build KubeJS scripts
              run: pnpm run build-dev  # meh, who cares about minaturising.
            
            - name: Build Quests
              run: ./build_quests.sh
            
            # TODO: add CI mode to Kamuidrome
            - name: Export Client-Side Modpack
              run: kamuidrome export --ci-mode BI-client
    
            - name: Upload client zip
              uses: "actions/upload-artifact@v4"
              with:
                name: "BI-${{ github.head_ref || github.ref_name }}-${{ github.sha }}.mrpack"
                path: "BI-client"
                compression-level: 9 
            
  
    build-mrpack-server:
        name: "Build .mrpack file (Server-side)"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v4"
              with:
                fetch-depth: 0

            - name: "Install Python"
              uses: actions/setup-python@v5
              with:
                # required for Kamuidrome
                python-version: "3.12" 

            - name: Install PNPM
              uses: pnpm/action-setup@v4

            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: "latest"
                cache: "pnpm"
            
            - name: Install Kamuidrome
              run: pip install -U git+https://github.com/Fuyukai/Kamuidrome.git
            
            - name: Build KubeJS scripts
              run: yarn run build-dev 
            
            - name: Build Quests
              run: ./build_quests.sh
            
            # TODO: add CI mode to Kamuidrome
            - name: Export Server-Side Modpack
              run: kamuidrome export BI-server --server-only --ci-mode
    
            - name: Upload server zip
              uses: "actions/upload-artifact@v4"
              with:
                name: "BI-${{ github.head_ref || github.ref_name }}-${{ github.sha }}-server.mrpack"
                path: "BI-server"
                compression-level: 9 
